version: "3.8"

services:
  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi9-slim
    container_name: im-mongo
    ports:
      - "27018:27017"
    volumes:
      - im_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: im_db

  redis:
    image: redis:8-alpine
    container_name: im-redis
    ports:
      - "6380:6379"
    volumes:
      - im_redis_data:/data

  nats:
    image: nats:2-alpine
    container_name: im-nats
    ports:
      - "4223:4222"
      - "8223:8222"
    command: "-js -m 8222 --user admin --pass admin"

volumes:
  im_mongo_data:
  im_redis_data:
